global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['localhost:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['localhost:8080']
  - job_name: aptos
      static_configs:
      - targets: ['localhost:9101']