version: '3.8'
services:
  vmauth:
    image: victoriametrics/vmauth:v1.78.1
    restart: always
    ports:
      - "8428:8427"
    volumes:
      - ./victoriametrics/vmauth.yml:/etc/vmauth.yml
    command:
      - "-auth.config=/etc/vmauth.yml"
    environment:
      AUTH_USER: ${AUTH_USER:-admin-doubletop}
      AUTH_PASSWORD: ${AUTH_PASSWORD:-doubletop}
  
  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.78.1
    restart: always
    expose:
      - "8428"
    volumes:
      - vmdata:/victoria-metrics-data
  
  vmagent:
    image: victoriametrics/vmagent:v1.78.1
    restart: always
    expose:
      - "8429"
    volumes:
      - vmagentdata:/vmagentdata
      - ./victoriametrics/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--remoteWrite.url=http://victoriametrics:8428/api/v1/write"
      - "--remoteWrite.label=hostname=${HOSTNAME:-monitoring}"

  grafana:
    image: grafana/grafana:9.0.2
    restart: always
    ports:
      - "80:3000"
    volumes:
      - grafanadata:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards:/var/lib/grafana/dashboards

volumes:
  vmdata:
  vmagentdata:
  grafanadata: