version: '3.8'
services:
  vmauth:
    image: victoriametrics/vmauth:v1.78.1
    labels: {monitoring: 'true'}
    restart: always
    ports:
      - "8428:8427"
    volumes:
      - ./victoriametrics/vmauth.yml:/etc/vmauth.yml
    command:
      - "-auth.config=/etc/vmauth.yml"
    environment:
      AUTH_USER: ${AUTH_USER:-admin-doubletop}
      AUTH_PASSWORD: ${AUTH_PASSWORD:-doubletop}
  
  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.78.1
    labels: {monitoring: 'true'}
    restart: always
    expose:
      - "8428"
    volumes:
      - vmdata:/victoria-metrics-data
  
  vmagent:
    image: victoriametrics/vmagent:v1.78.1
    labels: {monitoring: 'true'}
    hostname: ${HOSTNAME:-monitoring}
    restart: always
    expose:
      - "8429"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - vmagentdata:/vmagentdata
      - ./victoriametrics/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--remoteWrite.url=http://victoriametrics:8428/api/v1/write"
      - "--remoteWrite.label=hostname=monitoring"

  grafana:
    image: grafana/grafana:9.0.2
    labels: {monitoring: 'true'}
    restart: always
    ports:
      - "80:3000"
    volumes:
      - grafanadata:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards:/var/lib/grafana/dashboards
  
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.3.1
    labels: {monitoring: 'true'}
    command: 
      - '--path.rootfs=/host'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

volumes:
  vmdata:
  vmagentdata:
  grafanadata: